### ISSUE TITLE
Do you have any example of band convolution?

### ISSUE THREAD

**Issue by ghost** [rborrelli/molfc#1]
Dear Borrelli,

I saw the conv.f90 file in the source code. However, I do not know how to use this function to convolute simulated progressions. Could you please give me some tips?

Thank you

Nhan

**Comment by rborrelli** [comment]
In this case the program conv.f90 computes an exact convolution of two stick spectra. This is needed, for example, if you  compute the spectra at different level of approximation for different modes.

If you want to convolute a stick spectrum with a Gaussian function of a given width, you should give a look at the shape.f90 program.

At the moment I dont' have working examples. I'll provide them very soon. However if you look at the code you should be able to guess the format of the input files.

**Comment by ghost** [comment]
Hi Borrelli,

I am going to have a closer look at the shape.f90 program and try to do something with my works.

Many thanks,

Nhan
